apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-breeze-setting
spec:
  forms:
    - group: nav
      label: 导航
      formSchema:
        - $formkit: group
          name: right
          label: 导航栏右侧
          value:
            darkMode: true
          children:
            - $formkit: radio
              name: darkMode
              label: 切换模式
              help: 右上角切换主题模式按钮
              options:
                - label: 显示
                  value: true
                - label: 隐藏
                  value: false