apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-breeze-setting
spec:
  forms:
    - group: basics
      label: 基础
      formSchema:
        - $formkit: code
          name: siteTitle
          label: 站点名称
          placeholder: 请输入站点名称
          height: 80px
          language: html
          help: 支持 HTML 语法
        - $formkit: text
          name: roles
          label: 角色
          value: "Developer"
          placeholder: 请输入角色名称
          help: 多项请用#分隔，例如：Developer#Designer#Writer
        - $formkit: date
          name: siteStartTime
          label: 建站时间
          validation: required
          value: "2023-08-05"
          help: 注意，此项为必填项
        - $formkit: text
          name: icp
          label: ICP 备案
          placeholder: 请输入 ICP 备案号
          help: 格式：皖ICP备 xxxxxxxx 号
        - $formkit: text
          name: gongan
          label: 公安备案
          placeholder: 请输入公安备案号
          help: 格式：皖公网安备 xxxxxxxx 号
        - $formkit: url
          name: copyrightAgreement
          label: 版权协议
          placeholder: 请输入版权协议地址
          help: 文章模块声明版权，也会使用此协议

    - group: nav
      label: 导航
      formSchema:
        - $formkit: group
          name: right
          label: 导航栏右侧
          value:
            darkMode: true
          children:
            - $formkit: radio
              name: darkMode
              label: 切换模式
              help: 右上角切换主题模式按钮
              options:
                - label: 显示
                  value: true
                - label: 隐藏
                  value: false

    - group: index
      label: 主页
      formSchema:
        - $formkit: group
          name: social_media
          label: 社交媒体
          value:
            socialMedia:
          children:
            - $formkit: repeater
              name: socialMedia
              label: 列表
              value: [ ]
              children:
                - $formkit: radio
                  name: option_social_data
                  label: 类型
                  value: icon
                  help: "icon图标选择icon图标，svg代码或者图片(如果使用图片请输入完整img标签)选择自定义"
                  options:
                    - value: icon
                      label: icon图标
                    - value: custom
                      label: 自定义
                - $formkit: textarea
                  name: icon
                  help: "icon图标，svg代码，图片(如果使用图片请输入完整img标签)"
                  label: 图标
                  validation: "required"
                - $formkit: text
                  name: name
                  label: 名称
                  validation: "required"
                - $formkit: text
                  name: url
                  label: 链接
                  validation: "required"
