apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-breeze-setting
spec:
  forms:
    - group: basics
      label: 基础
      formSchema:
        - $formkit: code
          name: siteTitle
          label: 站点名称
          placeholder: 请输入站点名称
          height: 80px
          language: html
          help: 支持 HTML 语法
        - $formkit: text
          name: roles
          label: 角色
          value: "Developer"
          placeholder: 请输入角色名称
          help: 多项请用#分隔，例如：Developer#Designer#Writer
        - $formkit: date
          name: siteStartTime
          label: 建站时间
          validation: required
          value: "2023-08-05"
          help: 注意，此项为必填项
        - $formkit: text
          name: icp
          label: ICP 备案
          placeholder: 请输入 ICP 备案号
          help: 格式：皖ICP备 xxxxxxxx 号
        - $formkit: text
          name: gongan
          label: 公安备案
          placeholder: 请输入公安备案号
          help: 格式：皖公网安备 xxxxxxxx 号
        - $formkit: url
          name: copyrightAgreement
          label: 版权协议
          placeholder: 请输入版权协议地址
          help: 文章模块声明版权，也会使用此协议

    - group: nav
      label: 导航
      formSchema:
        - $formkit: group
          name: right
          label: 导航栏右侧
          value:
            darkMode: true
          children:
            - $formkit: radio
              name: darkMode
              label: 切换模式
              help: 右上角切换主题模式按钮
              options:
                - label: 显示
                  value: true
                - label: 隐藏
                  value: false
